### ISSUE TITLE
getting  Maximum call stack size exceeded of querySelector when React is being destructed 

### ISSUE THREAD

**Issue by guyschlider** [devilwjp/vuereact-combined#31]
Hi,

Wonder if anybody got a clue or idea, why when a Vue component is rendering a React component with `applyReactInVue` - when navigating away from the page, in the beforeDestroy of `applyReactInVue` we get an infinite loop of `Maximum call stack size exceeded`:

Uncaught RangeError: Maximum call stack size exceeded
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56360)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)
    at Object.keys.forEach.q.forEach.window.<computed>.<computed> [as querySelector] (chunk-vendors.cbee584d.js:107:56556)

**Comment by guyschlider** [comment]
Did some research,
looks like maybe 
https://github.com/gloriasoft/veaury/commit/5e2b320400ca96daccd6f75c21fdfea52fd6077a
is related?

**Comment by devilwjp** [comment]
@guyschlider It seems to be the same issue and will be fixed in the near future.

**Comment by guyschlider** [comment]
I can confirm it is the same issue and forking and updating those methods solve it

Thanks so much for your great work :)

**Comment by daydaychen** [comment]
@devilwjp 大佬这个问题有计划修复吗，我本想着自己构建下，但构建出来的产物报各种错误。。。
